### ISSUE TITLE
Production ready `symbology`

### ISSUE THREAD

**Issue by bkj** [gophronesis/ernest#12]
_From @bkj on March 23, 2016 13:19_

_Copied from original issue: bkj/edward#13_

**Comment by bkj** [comment]
attn @Emmett-Culhane 

In `ernest_forms_cat`, the record `edgar/data/1505984/0001505984-15-000001.txt` has ticker `PXYN`, but no entry in `ernest_symbology_cat` has ticker `PXYN`.

What's the explanation?

**Comment by Emmett-Culhane** [comment]
Ill have to check it out and get back to you.

**Comment by bkj** [comment]
I changed some of the code here and was unable to reproduce this bug.  Let's say this is good for now.
