### ISSUE TITLE
Add `not_analyzed` mapping to all indices

### ISSUE THREAD

**Issue by bkj** [gophronesis/ernest#21]
Need to add `not_analyzed` mapping to all indices so that we can treat strings as categorical variables.  This requires you to create a new index, set the mapping and reindex all of the data.

**Comment by bkj** [comment]
The ".cat" property should not be set for large text fields, like forum post bodies, OMX news articles, etc.  Setting it on those fields can cause errors at index time and probably bad effects on the size of the indexes.

**Comment by Emmett-Culhane** [comment]
Yeah I ran in to this issue and tried to implement this strategy. MSG field
in crowdsar and article in omx should be strings and not have cat mappings.

**Comment by Emmett-Culhane** [comment]
yes.

**Comment by Emmett-Culhane** [comment]
the del taco properties 1 limited partnership has not filed any ownership
documents

**Comment by bkj** [comment]
I think that comment is in the wrong issue
