### ISSUE TITLE
`ernest_xbrl_aqfs` problem

### ISSUE THREAD

**Issue by bkj** [gophronesis/ernest#50]
Seems like this index is causing some problems.  What is it?  Trying to open the index makes Elasticsearch hang, so I can't look at it.

If I'm not mistaken, this is some intermediate dataset that's required for computing some other things.  If we're not ever going to be querying it from the frontend, maybe it doesn't need to be stored in Elasticsearch.

**Comment by Emmett-Culhane** [comment]
You can just delete that for now it's isn't being used.
