### ISSUE TITLE
max clause count issue with es queries

### ISSUE THREAD

**Issue by Emmett-Culhane** [gophronesis/ernest#53]
cannot execute filtered queries on relatively small (3.6 mb) xbrl_enrich index because of max_clause_count parameter being too small (1024). Could change the parameter but there is no significant nesting of values and the documents are not of complex structures.

**Comment by bkj** [comment]
What's the use case in which you're submitting more than 1000 clauses in a
query?

**Comment by Emmett-Culhane** [comment]
I am not. It has something to do with the mechanics of how the query is
being dealt with by es.

post xbrl_enrich/_search
{
  "query" : {
    "filtered" : {
      "filter" : {
        "exists" : {
          "field" : "__meta__.financials"
        }
      }
    }
  }
}

**Comment by bkj** [comment]
Oh that's weird.  Let me take a look.

**Comment by bkj** [comment]
I think it has something to do with the number of possible subfields that `__meta__.financials` can have.  It works if you change it to 

```
POST xbrl_enrich/_search
{
  "query" : {
    "filtered" : {
      "filter" : {
        "exists" : {
          "field" : "__meta__.financials.assets"
        }
      }
    }
  }
}
```

But the general structure of the `__meta__.financials` field is a general problem.  I'd suggest changing it to be roughly like

```
"financials": {
  "liabilitiesCurrent": {
    "value"    : 12345,
    "type"     : ...
    "min_date" : 2015-01-01
    "max_date" : 2016-01-01
  },
```

Then we can always access the value with `__meta__.financials.whatever.value`, plus your queries will work again.

**Comment by bkj** [comment]
I think we learned our lesson
