### ISSUE TITLE
Date mapping

### ISSUE THREAD

**Issue by bkj** [gophronesis/ernest#58]
Make sure that dates and time are mapped as dates and times in all cases

`crowdsar_cat` is incorrectly mapped ATM

**Comment by MorganPeterson** [comment]
Let me know when and if this changes because it will change the way charts
are handled on the front end.

On Tue, Jun 7, 2016 at 10:51 AM, Ben Johnson <notifications@github.com>
wrote:

> Make sure that dates and time are mapped as dates and times in all cases
>
> crowdsar_cat is incorrectly mapped ATM
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/gophronesis/ernest/issues/58>, or mute the thread
> <https://github.com/notifications/unsubscribe/ALO_ckE-qKuVbXsN9bBDdssyf6vHMSeTks5qJYVigaJpZM4IwAmv>
> .
>



-- 
Morgan Peterson
Phronesis

**Comment by bkj** [comment]
@Emmett-Culhane Change it ASAP in that case

**Comment by bkj** [comment]
@MorganPeterson Presumably you mean because if it's properly mapped you'll be able to do aggregations in Elasticsearch rather than on the front end?

**Comment by MorganPeterson** [comment]
No. It has to do with field mapping when the data comes into the front end.
It caused me problems in the beginning because I was looking for a date
field when instead it was coming in as a time field.

On Tue, Jun 7, 2016 at 11:43 AM, Ben Johnson <notifications@github.com>
wrote:

> @MorganPeterson <https://github.com/MorganPeterson> Presumably you mean
> because if it's properly mapped you'll be able to do aggregations in
> Elasticsearch rather than on the front end?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/gophronesis/ernest/issues/58#issuecomment-224322270>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ALO_cpaWxYUqsjn2D4VsaQQ_V40s-x4uks5qJZGLgaJpZM4IwAmv>
> .
>



-- 
Morgan Peterson
Phronesis

**Comment by Emmett-Culhane** [comment]
Ok. The index is very big so it will take a little while to reindex once I
have reset the mappings.

**Comment by bkj** [comment]
Word.  There's enough disk space to make a copy.

**Comment by bkj** [comment]
Running right now
