### ISSUE TITLE
Financials mapping

### ISSUE THREAD

**Issue by bkj** [gophronesis/ernest#63]
What are the `to`, `from` and `context` fields in the `financials` mapping?

**Comment by Emmett-Culhane** [comment]
The date range of the fact, and the name of the context for the specific
fact. Some facts have multiple contexts for year to date values and the
previous years values and those fields are what I used to eliminate the
duplicate facts.

**Comment by bkj** [comment]
OK.  Also, can you add a `__meta__.has_financials` field when you add financials?  This speeds up `{"filtered" : {"exists" : ...}}` queries, for the "mapping explosion" reason that we've talked about previously.

**Comment by Emmett-Culhane** [comment]
Can do.

**Comment by Emmett-Culhane** [comment]
the way the docs are processed now is that they are downloaded / parsed / written to raw / used to enrich financials in the ernest_aq_forms_enrich_cat index. I run an interpolation on that index to back in to certain high level balance sheet items & add a tag "__meta__.financials.interpolated" to the doc. This is a t/f bool value, which could be used to proxy the has financials key suggested above.
